---
- name: Install Docker on Rhel8
  hosts: all
  become: yes
  gather_facts: false

  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_yum_repo_url: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    docker_yum_repo_enable_nightly: '0'
    docker_yum_repo_enable_test: '0'
    docker_yum_gpg_key: https://download.docker.com/linux/centos/gpg
    iptables_yum_package: iptables-services

  tasks:
    - name: Add Docker GPG key.
      rpm_key:
        key: "{{ docker_yum_gpg_key }}"
        state: present

    - name: Add Docker repository
      yum_repository:
        name: "{{ docker_package }}"
        description: Docker CE Stable - $basearch 
        baseurl: "{{ docker_yum_repo_url }}"
        enabled: yes
        gpgkey: "{{ docker_yum_gpg_key }}"
        gpgcheck: yes

    - name: Install iptables
      yum:
        name: "{{ iptables_yum_package }}"
        state: present

    - name: Install Docker
      yum: 
        name: "{{ docker_package }}"   
        state: present
        update_cache: true    

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      
    - name: Add user ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

