---
- name:  Python libraries installed.
  apt:
    name: "{{ postgresql_python_library }}"
    state: present

- name: Postgres packages installed.
  apt:
    name: "{{ postgresql_packages }}"
    state: present

- name:  Postgres started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"    

- name:  Postgres add worker users.
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    #    role_attr_flags: "CREATEDB,NOSUPERUSER"
  become: true
  become_user: "{{ postgresql_user }}"

- name: Postgres add worker databases .
  postgresql_db:
    name: "{{ db_name }}"
    #    login_password: 
    login_user: "{{ postgresql_user }}"
  become: true
  become_user: "{{ postgresql_user }}"

- name:  access from worker users.
  postgresql_privs:
    db: "{{ db_name }}"
    role: "{{ db_user }}"
    objs: "{{ db_objs }}"
    privs: "{{ db_privs }}"  
  become: true
  become_user: "{{ postgresql_user }}"  
