- block: #=== Block for Redhat ===
    - name: Packages Installed
      yum: name={{ packages }} 

    - name: PHP Packages Installed
      yum: name={{ php_packages }}

    - name: Start and enabled on boot Web Server
      service: name=httpd state=started enabled=yes

    - name: start mysql server and enable it on reboot
      service: name=mariadb state=started enabled=true

    - name: Selinux time disabled
      shell: setenforce 0

    - name: Bacula Packages Installed
      dnf: name={{ bacula_packages }}

    - name: Copy Distributiv  and contig apache to Server 
      copy: src={{ item }} dest={{ destin_folder }} mode=0555
      loop:
        - "webacula.zip"
        - "webacula.conf"  

    - name: Copy Distributiv  and contig apache to Server
      copy: src={{ item }} dest={{ destin_folder_config }} mode=0555
      loop:
        - "bacula-dir.conf"
        - "bacula-fd.conf"
        - "bacula-sd.conf"
        - "bconsole.conf"  

          #    - name: Selinux time enabled
          #      shell: setenforce 1

    - name: Unarchive Apps Webacula
      unarchive:
        src: webacula.zip
        dest: /var/www/html/
        owner: apache
        group: apache
        # remote_src: yes

    - name: Set selinux policy for directories
      sefcontext:
        target: '/var/www/html/webacula/data/cache(/.*)?'
        setype: "httpd_cache_t"
        reload: True
        state: present
    
    - name: Set selinux policy for bconsole
      sefcontext:
        target: '/etc/bacula/bconsole.conf'
        setype: "httpd_cache_t"
        reload: True
        state: present 

    - name: Run restore context to reload selinux
      shell: restorecon -Rv /var/www/html

    - name: Run restore context to reload selinux
      shell: restorecon -Rv /etc/bacula/bconsole.conf

    - name: Copy config files
      copy: src=webacula.conf dest=/etc/httpd/conf.d/webacula.conf owner=apache group=apache mode=0664

    - name: Remove the MySQL test database.
      mysql_db: db=test state=absent

    - name: Create a database for bacula.
      mysql_db: "db=bacula state=present"  

    - name: Add bacula user and all privileges  
      mysql_user: name=bacula password='*2D34C81704AD060D038AB7B0540EE0757B93B42B' encrypted=yes priv='*.*:ALL' state=present      
    
    - name: Create tables bacula
      shell: /usr/libexec/bacula/make_mysql_tables
    
    - name: Create tables webacula
      shell: /var/www/html/webacula/install/MySql/10_make_tables.sh

    - name: Create acl tables webacula
      shell: /var/www/html/webacula/install/MySql/20_acl_make_tables.sh  
   
    - name: fix bag 1022 version remove old item
      community.mysql.mysql_query:
        login_db: bacula
        query: DELETE FROM bacula.webacula_version

    - name: fix bag 1022 version add new item
      community.mysql.mysql_query:
        login_db: bacula
        query: INSERT INTO bacula.webacula_version (`versionId`) VALUES ('1022')   
    
    - name: add mysql libccats.so
      shell: alternatives --set libbaccats.so /usr/lib64/libbaccats-mysql.so

    - name: Add permissions bconsole for sbin
      file: path=/usr/sbin/bconsole  owner=root group=bacula mode=755

    - name: Add permissions bconsole for config
      file: path=/etc/bacula/bconsole.conf  owner=root group=bacula mode=755  

    - name: Open port 80 for http access
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: Restart the firewalld 
      service: 
        name: firewalld 
        state: restarted

    - name: Start and enabled on boot bacula service
      service: name={{ item }} state=started enabled=yes
      loop:
        - "bacula-dir"
        - "bacula-sd"
        - "bacula-fd"  
      notify: Restart Apache RedHat 

      # selinux
      # semanage fcontext -l | grep bacula
      # semanage port -l | grep -w bacula_port_t
      # semanage port -l |grep 9101
      # semanage port -m -t bacula_port_t -p tcp 9101
  


