- block: #=== Block for Redhat ===
    - name: Packages Installed
      yum: name={{ packages }} 

    - name: PHP Packages Installed
      yum: name={{ php_packages }}

    - name: Bacula Packages Installed
      dnf: name={{ bacula_packages }}  

    - name: Start and enabled on boot Web Server
      service: name=httpd state=started enabled=yes

    - name: start mysql server and enable it on reboot
      service: name=mariadb state=started enabled=true
    - name: Copy Distributiv Glpi and dump db to Server 
      copy: src={{ item }} dest={{ destin_folder }} mode=0555
      loop:
        - "webacula.zip"
        - "webacula.conf"  

    - name: Unarchive Apps Webacula
      unarchive:
        src: webacula.zip
        dest: /var/www/html/
        owner: apache
        group: apache
        # remote_src: yes

    - name: Copy config files
      copy: src=webacula.conf dest=/etc/httpd/conf.d/webacula.conf owner=apache group=apache mode=0664

    - name: Remove the MySQL test database.
      mysql_db: db=test state=absent

    - name: Create a database for bacula.
      mysql_db: "db=bacula state=present"  

    - name: Add bacula user and all privileges  
      mysql_user: name=bacula password='*2D34C81704AD060D038AB7B0540EE0757B93B42B' encrypted=yes priv='*.*:ALL' state=present      
    
    - name: Create tables bacula
      shell: /usr/libexec/bacula/make_mysql_tables
    
    - name: Create tables webacula
      shell: /var/www/html/webacula/install/MySql/10_make_tables.sh

    - name: Create acl tables webacula
      shell: /var/www/html/webacula/install/MySql/20_acl_make_tables.sh  
   
    - name: fix bag 1022 version remove old item
      community.mysql.mysql_query:
        login_db: bacula
        query: DELETE FROM bacula.webacula_version

    - name: fix bag 1022 version add new item
      community.mysql.mysql_query:
        login_db: bacula
        query: INSERT INTO bacula.webacula_version (`versionId`) VALUES ('1022')   
    
    - name: add mysql libccats.so
      shell: alternatives --set libbaccats.so /usr/lib64/libbaccats-mysql.so

    - name: Add permissions bconsole for sbin
      file: path=/usr/sbin/bconsole  owner=root group=bacula mode=u+rwx,g+rx,o-rwx

    - name: Add permissions bconsole for config
      file: path=/etc/bacula/bconsole.conf  owner=root group=bacula mode=u=rw,g=r,o-rwx  

    - name: enable port  80
      firewalld:
        zone: public
        port: 80/tcp
        permanent: true
        state: enabled    
      #  chown root:bacula /usr/sbin/bconsole
      #  chmod u=rwx,g=rx,o= /usr/sbin/bconsole
      #  chown root:bacula /etc/bacula/bconsole.conf
      #  chmod u=rw,g=r,o= /etc/bacula/bconsole.conf
      #  systemctl stop firewalld  


