---
# defaults file for deploy_prometeus_grafana
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_yum_repo_url: https://download.docker.com/linux/centos/$releasever/$basearch/stable
docker_yum_repo_enable_nightly: '0'
docker_yum_repo_enable_test: '0'
docker_yum_gpg_key: https://download.docker.com/linux/centos/gpg
iptables_yum_package: iptables-services
prometheus_home: /opt/prometheus
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_configs: /etc/prometheus
prometheus_data_mount_path: 
grafana_configs: /etc/grafana
