 - name:  Create Users & Groups
   user:
     name: "{{ exporter_user }}"
     state: present
     shell: /bin/false
     system: yes
     #     append: yes
     #     groups: "{{ exporter_group }}"

 - name: Copy node_exporter to Server 
   copy: src={{ node_exporter }} dest={{ run_path }}  owner={{ exporter_user }} group={{ exporter_user }} mode=0554

 - name: Copy config start service  to Server
   copy: src={{ node_exporter_service }} dest={{ system_path }}  

 - name: Start the node_exporter service
   service: name=node_exporter state=started daemon_reload=yes enabled=yes 

